# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.runs/synth_1/.Xil/Vivado-12284-LAPTOP-3TB8KCCP/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tcsg324-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {{D:/Program Files/Verilog project/MIPS_MultiCycle/MIPS_MultiCycle.srcs/sources_1/imports/Desktop}} {
      {D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.srcs/sources_1/imports/new/Hex7Seg.sv}
      {D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.srcs/sources_1/imports/new/IO.sv}
      {D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.srcs/sources_1/imports/new/adder.sv}
      {D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.srcs/sources_1/imports/new/al2.sv}
      {D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.srcs/sources_1/imports/new/alu.sv}
      {D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.srcs/sources_1/imports/new/aludec.sv}
      {D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.srcs/sources_1/imports/new/controller.sv}
      {D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.srcs/sources_1/imports/new/dMemoryDecoder.sv}
      {D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.srcs/sources_1/imports/new/datapath.sv}
      {D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.srcs/sources_1/imports/new/dmem.sv}
      {D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.srcs/sources_1/new/eqcmp.sv}
      {D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.srcs/sources_1/imports/new/flopr.sv}
      {D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.srcs/sources_1/new/hazard.sv}
      {D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.srcs/sources_1/imports/new/imem.sv}
      {D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.srcs/sources_1/imports/new/maindec.sv}
      {D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.srcs/sources_1/imports/new/mips.sv}
      {D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.srcs/sources_1/imports/new/mux2.sv}
      {D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.srcs/sources_1/new/mux4.sv}
      {D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.srcs/sources_1/imports/new/mux7Seg.sv}
      {D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.srcs/sources_1/imports/new/regfile.sv}
      {D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.srcs/sources_1/imports/new/signext.sv}
      {D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.srcs/sources_1/imports/new/zeronext.sv}
      {D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.srcs/sources_1/imports/new/top.sv}
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList {{D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.runs/synth_1/.Xil/Vivado-12284-LAPTOP-3TB8KCCP/realtime/top_synth.xdc}}
    rt::sdcChecksum
    set rt::top top
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.cache/wt}
    rt::set_parameter enableSplitFlowPath "D:/Program Files/Verilog project/MIPS_Pipeline/MIPS_Pipeline.runs/synth_1/.Xil/Vivado-12284-LAPTOP-3TB8KCCP/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
